const express=require('express');
const asyncHandler=require('../../utils/async-handler');
const ApiError=require('../../utils/api-error');
const C=require('./counter-core');
const M=require('./management.service');
const checkout=require('./checkout.service');
const stock=require('./stock-bakery.service');
const catalog=require('./catalog.service');
const offline=require('./offline.service');
const reports=require('./reports.service');
const {getPagination,buildMeta}=require('../../utils/pagination');
const router=express.Router();
const contract=[];
router.use(require('../../middleware/authentication'));
router.use(asyncHandler(async(req,res,next)=>{req.counter=await M.context(req.user);next();}));
const key=req=>req.get('Idempotency-Key');
contract.push({method:'get',path:'/me'});
router.get('/me',asyncHandler(async(req,res)=>res.json({success:true,data:{id:req.counter.id,store_id:req.counter.storeId,operational_role:req.counter.role,permissions:await require('../access-control/require-permission').getUserPermissions(req.user.groupId)}})));
function route(method,path,permission,fn) {
  contract.push({method,path,permission});
  router[method](path,require('../access-control/require-permission').requirePermission(permission),asyncHandler(async(req,res)=>{const schema=require('./api-contract').bodies[`${method} ${path}`];if(schema)require('./api-contract').validate(schema,req.body);res.json({success:true,data:await fn(req),message:'OK'});}));
}
function list(table,roles,extra='') {
  return async req=>{
    C.role(req.counter,roles);const {page,limit,offset}=getPagination(req.query);
    const [rows]=await req.counter.pool.query(`SELECT * FROM ${table} WHERE store_id=?${extra} ORDER BY id DESC LIMIT ? OFFSET ?`,[req.counter.storeId,limit,offset]);
    const [[total]]=await req.counter.pool.query(`SELECT COUNT(*) AS n FROM ${table} WHERE store_id=?${extra}`,[req.counter.storeId]);return {rows,meta:buildMeta(page,limit,total.n)};
  };
}
route('get','/settings','ACCESS.SETUP.READ',req=>M.getSettings(req.counter));
route('patch','/settings','ACCESS.SETUP.UPDATE',req=>M.updateSettings(req.counter,req.body,key(req)));
route('get','/staff','ACCESS.USER_GROUPS.READ',async req=>{C.role(req.counter,['owner']);const [rows]=await req.counter.pool.query('SELECT s.user_id,s.role,s.is_active,u.full_name,u.username,u.group_id FROM store_staff s JOIN users u ON u.id=s.user_id WHERE s.store_id=? ORDER BY u.id',[req.counter.storeId]);return rows;});
route('post','/staff','ACCESS.USER_GROUPS.UPDATE',req=>M.assignStaff(req.counter,req.body,key(req)));
// Switching remains possible for a cashier without staff-management permission.
contract.push({method:'post',path:'/staff/switch'});
router.post('/staff/switch',asyncHandler(async(req,res)=>{require('./api-contract').validate(require('./api-contract').bodies['post /staff/switch'],req.body);res.json({success:true,data:await M.switchPin(req.counter,req.body)});}));
route('post','/approvals','ACCESS.SALES.UPDATE',req=>M.approve(req.counter,req.body,key(req)));
route('get','/registers','ACCESS.SALES.READ',list('registers',['owner','manager','cashier','inventory_clerk']));
route('post','/registers','ACCESS.SETUP.CREATE',req=>M.register(req.counter,req.body,key(req)));
route('get','/shifts','ACCESS.SALES.READ',async req=>{C.role(req.counter,['owner','manager','cashier']);const {limit,offset}=getPagination(req.query);const [rows]=await req.counter.pool.query(`SELECT * FROM register_shifts WHERE store_id=?${req.counter.role==='cashier'?' AND opened_by=?':''} ORDER BY id DESC LIMIT ? OFFSET ?`,[req.counter.storeId,...(req.counter.role==='cashier'?[req.counter.id]:[]),limit,offset]);return {rows};});
route('post','/shifts','ACCESS.SALES.CREATE',req=>M.openShift(req.counter,req.body,key(req)));
route('post','/shifts/:id/close','ACCESS.SALES.CREATE',req=>M.closeShift(req.counter,req.params.id,req.body,key(req)));
route('post','/cash-movements','ACCESS.FINANCE.CREATE',req=>M.cashMovement(req.counter,req.body,key(req)));
route('get','/checkouts','ACCESS.SALES.READ',async req=>{const {limit,offset}=getPagination(req.query);C.role(req.counter,['owner','manager','cashier']);const status=req.query.status;if(status)C.choice(status,['draft','held','pending_payment','completed','voided'],'status');const [rows]=await req.counter.pool.query(`SELECT * FROM checkout_sessions WHERE store_id=?${req.counter.role==='cashier'?' AND cashier_id=?':''}${status?' AND status=?':''} ORDER BY id DESC LIMIT ? OFFSET ?`,[req.counter.storeId,...(req.counter.role==='cashier'?[req.counter.id]:[]),...(status?[status]:[]),limit,offset]);return {rows};});
route('post','/checkouts','ACCESS.SALES.CREATE',req=>checkout.create(req.counter,req.body,key(req)));
route('get','/checkouts/:id','ACCESS.SALES.READ',req=>checkout.get(req.counter,req.params.id));
route('patch','/checkouts/:id','ACCESS.SALES.CREATE',req=>checkout.patch(req.counter,req.params.id,req.body,key(req)));
route('post','/checkouts/:id/state','ACCESS.SALES.CREATE',req=>checkout.transition(req.counter,req.params.id,req.body,key(req)));
route('post','/checkouts/:id/payments','ACCESS.SALES.CREATE',req=>checkout.payment(req.counter,req.params.id,req.body,key(req)));
route('post','/checkouts/:id/complete','ACCESS.SALES.CREATE',req=>checkout.complete(req.counter,req.params.id,req.body,key(req)));
route('post','/payments/:id/confirm','ACCESS.SALES.CREATE',req=>checkout.confirm(req.counter,req.params.id,req.body,key(req)));
route('post','/payments/:id/cancel','ACCESS.SALES.CREATE',req=>checkout.cancelPayment(req.counter,req.params.id,req.body,key(req)));
route('get','/payment-providers','ACCESS.SALES.READ',list('payment_providers',['owner','manager','cashier']));
route('post','/payment-providers','ACCESS.SETUP.CREATE',req=>C.transaction(req.counter,'provider.create',key(req),req.body,async conn=>{C.role(req.counter,['owner']);C.choice(req.body.method,['card','bank_transfer','wallet'],'method');C.choice(req.body.mode,['recorded','sandbox'],'mode');const value=await C.insert(conn,'payment_providers',{store_id:req.counter.storeId,code:C.text(req.body.code,'provider code',60),method:req.body.method,mode:req.body.mode,is_enabled:req.body.is_enabled===true?1:0,configuration:JSON.stringify({})});await C.audit(conn,req.counter,'provider.create','provider',value,'Public recorded/sandbox provider configured');return C.row(conn,'payment_providers',req.counter.storeId,value);}));
route('get','/receipts/:id','ACCESS.SALES.READ',req=>checkout.receipt(req.counter,req.params.id));
route('post','/receipts/:id/reprint','ACCESS.SALES.PRINT',req=>C.transaction(req.counter,'receipt.reprint',key(req),{id:req.params.id,...req.body},async conn=>{C.role(req.counter,['owner','manager']);await C.row(conn,'sale_invoices',req.counter.storeId,req.params.id);await C.audit(conn,req.counter,'receipt.reprint','sale_invoice',req.params.id,C.text(req.body.reason,'reprint reason'));return {invoice_id:Number(req.params.id),reprint:true};}));
route('post','/refunds','ACCESS.FINANCE.CREATE',req=>require('./refund.service').refund(req.counter,req.body,key(req)));
route('post','/exchanges','ACCESS.FINANCE.CREATE',req=>require('./refund.service').exchange(req.counter,req.body,key(req)));
route('get','/refunds','ACCESS.FINANCE.READ',list('refund_notes',['owner','manager']));
route('post','/stock-adjustments','ACCESS.STOCK.CREATE',req=>stock.adjustment(req.counter,req.body,key(req)));
route('get','/stock-adjustments','ACCESS.STOCK.READ',list('stock_adjustments',['owner','manager','inventory_clerk']));
route('get','/stock/reconcile','ACCESS.STOCK.READ',req=>reports.reconcile(req.counter));
route('get','/catalog/search','ACCESS.ITEMS.READ',req=>catalog.search(req.counter,req.query));
route('get','/customers','ACCESS.CUSTOMERS.READ',list('customers',['owner','manager','cashier']));
route('post','/customers','ACCESS.CUSTOMERS.CREATE',req=>require('./customers.service').save(req.counter,null,req.body,key(req)));
route('patch','/customers/:id','ACCESS.CUSTOMERS.UPDATE',req=>require('./customers.service').save(req.counter,req.params.id,req.body,key(req)));
route('get','/customers/:id/history','ACCESS.CUSTOMERS.READ',req=>require('./customers.service').history(req.counter,req.params.id));
route('post','/catalog/variants','ACCESS.ITEMS.CREATE',req=>catalog.variant(req.counter,req.body,key(req)));
route('post','/catalog/import','ACCESS.ITEMS.CREATE',req=>catalog.importCsv(req.counter,req.body,key(req)));
router.get('/catalog/export',require('../access-control/require-permission').requirePermission('ACCESS.ITEMS.READ'),asyncHandler(async(req,res)=>res.type('text/csv').attachment('brightpos-catalog.csv').send(await catalog.exportCsv(req.counter))));
contract.push({method:'get',path:'/catalog/export',permission:'ACCESS.ITEMS.READ'});
route('get','/catalog/:id/label','ACCESS.ITEMS.READ',async req=>{const item=await C.row(req.counter.pool,'item_details',req.counter.storeId,req.params.id);return {item_id:item.id,name:item.item_name,sku:item.sku,barcode:item.label_barcode,sale_price:item.sale_price,format:'code128',output:'structured label data'};});
route('post','/coupons','ACCESS.SETUP.CREATE',req=>C.transaction(req.counter,'coupon.create',key(req),req.body,async conn=>{C.role(req.counter,['owner']);const b=req.body;C.choice(b.discount_type,['percent','fixed'],'discount type');const value=C.exact.scaled(b.discount_value);if(!value||(b.discount_type==='percent'&&value>10000n))throw new ApiError(422,'Invalid coupon value');const start=new Date(b.valid_from),end=b.valid_until?new Date(b.valid_until):null;if(!Number.isFinite(start.getTime())||(end&&(!Number.isFinite(end.getTime())||end<=start)))throw new ApiError(422,'Invalid coupon dates');const coupon=await C.insert(conn,'coupons',{store_id:req.counter.storeId,code:C.text(b.code,'coupon code',60),discount_type:b.discount_type,discount_value:C.exact.decimal(value),minimum_spend_minor:C.exact.integer(b.minimum_spend_minor || 0),maximum_uses:b.maximum_uses?C.exact.integer(b.maximum_uses,'maximum_uses',true):null,valid_from:start,valid_until:end});await C.audit(conn,req.counter,'coupon.create','coupon',coupon,'Coupon created');return C.row(conn,'coupons',req.counter.storeId,coupon);}));
route('get','/recipes','ACCESS.STOCK.READ',list('recipe_versions',['owner','manager','inventory_clerk']));
route('get','/recipes/:id','ACCESS.STOCK.READ',async req=>{C.role(req.counter,['owner','manager','inventory_clerk']);const recipe=await C.row(req.counter.pool,'recipe_versions',req.counter.storeId,req.params.id);const [ingredients]=await req.counter.pool.query('SELECT * FROM recipe_ingredients WHERE store_id=? AND recipe_id=?',[req.counter.storeId,recipe.id]);return {...recipe,ingredients};});
route('post','/recipes','ACCESS.STOCK.CREATE',req=>stock.recipe(req.counter,req.body,key(req)));
route('post','/production','ACCESS.STOCK.CREATE',req=>stock.production(req.counter,req.body,key(req)));
route('get','/production','ACCESS.STOCK.READ',list('production_runs',['owner','manager','inventory_clerk']));
route('post','/bakery-orders/:id','ACCESS.BOOKINGS.UPDATE',req=>stock.bakeryOrder(req.counter,req.params.id,req.body,key(req)));
route('post','/bookings','ACCESS.BOOKINGS.CREATE',req=>require('./booking.service').create(req.counter,req.body,key(req)));
route('post','/bookings/:id/deposits','ACCESS.BOOKINGS.CREATE',req=>require('./booking.service').deposit(req.counter,req.params.id,req.body,key(req)));
route('post','/bookings/:id/convert','ACCESS.BOOKINGS.CREATE',req=>require('./booking.service').convert(req.counter,req.params.id,req.body,key(req)));
route('get','/bookings','ACCESS.BOOKINGS.READ',list('bookings',['owner','manager','cashier']));
route('get','/bakery-orders','ACCESS.BOOKINGS.READ',list('bakery_order_details',['owner','manager','cashier']));
route('post','/offline/allocations','ACCESS.STOCK.CREATE',req=>offline.allocation(req.counter,req.body,key(req)));
route('post','/offline/allocations/:id/release','ACCESS.STOCK.UPDATE',req=>offline.release(req.counter,req.params.id,req.body,key(req)));
route('post','/offline/sync','ACCESS.SALES.CREATE',req=>offline.sync(req.counter,req.body,key(req)));
route('get','/offline/state','ACCESS.SALES.READ',req=>offline.state(req.counter,req.query.register_id,req.get('X-Register-Device')));
route('post','/offline/transactions/:id/discard','ACCESS.STOCK.UPDATE',req=>offline.discard(req.counter,req.params.id,req.body,key(req)));
route('get','/offline/transactions','ACCESS.SALES.READ',list('offline_transactions',['owner','manager']));
route('get','/reports','ACCESS.DASHBOARD.READ',req=>reports.report(req.counter,req.query));
router.get('/reports/export',require('../access-control/require-permission').requirePermission('ACCESS.DASHBOARD.READ'),asyncHandler(async(req,res)=>res.type('text/csv').attachment('brightpos-counter-report.csv').send(await reports.exportCsv(req.counter,req.query))));
contract.push({method:'get',path:'/reports/export',permission:'ACCESS.DASHBOARD.READ'});
route('get','/audit','ACCESS.SECURITY.READ',list('audit_events',['owner']));
route('get','/notifications','ACCESS.DASHBOARD.READ',async req=>{C.role(req.counter,['owner','manager','cashier','inventory_clerk']);const {limit,offset}=getPagination(req.query);const [rows]=await req.counter.pool.query('SELECT * FROM notifications WHERE store_id=? AND (recipient_id=? OR (recipient_id IS NULL AND (recipient_role IS NULL OR recipient_role=?))) ORDER BY id DESC LIMIT ? OFFSET ?',[req.counter.storeId,req.counter.id,req.counter.role,limit,offset]);return {rows};});
route('post','/notifications/:id/read','ACCESS.DASHBOARD.READ',req=>C.transaction(req.counter,'notification.read',key(req),{id:req.params.id},async conn=>{const notice=await C.row(conn,'notifications',req.counter.storeId,req.params.id,true);if(notice.recipient_id!==null&&notice.recipient_id!==req.counter.id||notice.recipient_id===null&&notice.recipient_role!==null&&notice.recipient_role!==req.counter.role)throw new ApiError(403,'Notification not addressed to this staff member');await conn.query('UPDATE notifications SET read_at=NOW() WHERE id=?',[notice.id]);return {id:notice.id,read:true};}));
module.exports=router;
module.exports.contract=contract;
