-- 0019_create_item_details.sql
-- Ordered fresh-install baseline. Do not edit after applying.
CREATE TABLE `item_details` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_name` varchar(200) NOT NULL,
  `item_image_url` varchar(500) DEFAULT NULL,
  `label_barcode` varchar(100) DEFAULT NULL,
  `item_category_id` INT UNSIGNED DEFAULT NULL,
  `manufacturer_id` INT UNSIGNED DEFAULT NULL,
  `supplier_id` INT UNSIGNED DEFAULT NULL,
  `shelve_location_id` INT UNSIGNED DEFAULT NULL,
  `item_unit_id` INT UNSIGNED DEFAULT NULL,
  `details` text DEFAULT NULL,
  `is_enable` tinyint(1) UNSIGNED NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `purchase_price` decimal(10,2) DEFAULT 0.00,
  `sale_price` decimal(10,2) DEFAULT 0.00,
  `stock` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `reorder_level` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `per_unit` INT NOT NULL DEFAULT 1,
  `item_subcategory_id` INT UNSIGNED DEFAULT NULL,
  `item_type_id` INT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `label_barcode` (`label_barcode`),
  KEY `fk_id_category` (`item_category_id`),
  KEY `fk_id_manuf` (`manufacturer_id`),
  KEY `fk_id_supplier` (`supplier_id`),
  KEY `fk_id_shelve` (`shelve_location_id`),
  KEY `fk_id_unit` (`item_unit_id`),
  KEY `idx_id_barcode` (`label_barcode`),
  KEY `fk_item_subcategory` (`item_subcategory_id`),
  KEY `fk_item_type` (`item_type_id`),
  CONSTRAINT fk_item_details_item_category_id FOREIGN KEY (item_category_id) REFERENCES categories(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_item_details_item_subcategory_id FOREIGN KEY (item_subcategory_id) REFERENCES sub_categories(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_item_details_manufacturer_id FOREIGN KEY (manufacturer_id) REFERENCES manufacturers(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_item_details_supplier_id FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_item_details_shelve_location_id FOREIGN KEY (shelve_location_id) REFERENCES shelve_locations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_item_details_item_unit_id FOREIGN KEY (item_unit_id) REFERENCES item_units(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_item_details_item_type_id FOREIGN KEY (item_type_id) REFERENCES item_types(id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
