-- Database phase: additive upgrade; preserve applied migrations and existing data.
CREATE TABLE checkout_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  store_id INT UNSIGNED NOT NULL DEFAULT 1,
  public_id CHAR(36) NOT NULL,
  status ENUM('draft','held','pending_payment','completed','voided') NOT NULL DEFAULT 'draft',
  subtotal_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
  discount_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
  total_minor BIGINT UNSIGNED NOT NULL DEFAULT 0,
  rounding_minor BIGINT NOT NULL DEFAULT 0,
  notes TEXT NULL,
  held_name VARCHAR(150) NULL,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  completed_at DATETIME NULL,
  void_reason VARCHAR(500) NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  register_id BIGINT UNSIGNED NOT NULL,
  cashier_id INT NOT NULL,
  shift_id BIGINT UNSIGNED NULL,
  customer_id INT UNSIGNED NULL,
  invoice_id INT UNSIGNED NULL,
  coupon_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_checkout_sessions_store_row (store_id, id),
  UNIQUE KEY uq_checkout_public (public_id),
  UNIQUE KEY uq_checkout_invoice (store_id, invoice_id),
  KEY idx_checkout_register_status (store_id, register_id, status),
  CONSTRAINT chk_checkout_discount CHECK (discount_minor <= subtotal_minor),
  CONSTRAINT chk_checkout_completed CHECK (status <> 'completed' OR (invoice_id IS NOT NULL AND completed_at IS NOT NULL)),
  CONSTRAINT fk_checkout_sessions_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_checkout_sessions_register_id FOREIGN KEY (store_id, register_id) REFERENCES registers(store_id, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_checkout_sessions_cashier_id FOREIGN KEY (store_id, cashier_id) REFERENCES users(store_id, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_checkout_sessions_shift_id FOREIGN KEY (store_id, shift_id) REFERENCES register_shifts(store_id, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_checkout_sessions_customer_id FOREIGN KEY (store_id, customer_id) REFERENCES customers(store_id, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_checkout_sessions_invoice_id FOREIGN KEY (store_id, invoice_id) REFERENCES sale_invoices(store_id, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_checkout_sessions_coupon_id FOREIGN KEY (store_id, coupon_id) REFERENCES coupons(store_id, id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

