const router=require('express').Router();
const controller=require('./booking-payment.controller');
router.param('id',(req,res,next,value)=>{try{req.params.id=require('../../utils/validation').id(value);next();}catch(e){next(e);}});
router.use(...require('../../middleware/protect-resource')('BOOKINGS'));
router.get('/',controller.list);
router.get('/:id',controller.getOne);
router.post('/',controller.create);
router.put('/:id',controller.update);
router.delete('/:id',controller.remove);
module.exports=router;
