const {test}=require('node:test');
const assert=require('node:assert/strict');
const {pbkdf2Sync,randomBytes}=require('node:crypto');
const {tables,verify,validateDocument,authorizeChanges}=require('../../src/modules/workspaces/workspace-validation');
function document(){const value=Object.fromEntries(tables.map(t=>[t,[]]));return {...value,version:2,workspaceId:'workspace',settings:[{id:'workspace',workspaceId:'workspace'}],staff:[{id:'owner',workspaceId:'workspace',role:'Owner'},{id:'cashier',workspaceId:'workspace',role:'Cashier'}],products:[{id:'coffee',workspaceId:'workspace',stock:10,lowStock:2,price:500,cost:100}]};}
test('workspace password verification matches Web Crypto PBKDF2 and rejects wrong passwords',async()=>{const salt=randomBytes(16),credential={salt:[...salt],hash:[...pbkdf2Sync('strong-password',salt,210000,32,'sha256')]};assert.equal(await verify('strong-password',credential),true);assert.equal(await verify('wrong-password',credential),false);assert.equal(await verify('anything',{salt:[],hash:[]}),false);});
test('workspace validation rejects foreign records and invalid money',()=>{const valid=document();assert.doesNotThrow(()=>validateDocument(valid,'workspace'));const foreign=structuredClone(valid);foreign.products[0].workspaceId='another-store';assert.throws(()=>validateDocument(foreign,'workspace'));const badMoney=structuredClone(valid);badMoney.products[0].price=1.5;assert.throws(()=>validateDocument(badMoney,'workspace'));});
test('cashier synchronization cannot edit prices, elevate a role, or decrement stock without a sale',()=>{const before=document(),cashier=before.staff[1];for(const mutate of [d=>d.products[0].price=0,d=>d.staff[1].role='Owner',d=>d.products[0].stock--]){const after=structuredClone(before);mutate(after);assert.throws(()=>authorizeChanges(before,after,cashier),/role/);}const sale=structuredClone(before);sale.orders.push({id:'sale',workspaceId:'workspace',cashierId:'cashier',status:'Paid',items:[{productId:'coffee',quantity:1}],total:500});sale.products[0].stock--;assert.doesNotThrow(()=>authorizeChanges(before,sale,cashier));});
test('manager cannot edit settings or permanently delete catalog records',()=>{const before=document(),after=structuredClone(before);after.settings[0].taxRate=0;assert.throws(()=>authorizeChanges(before,after,{id:'manager',role:'Manager'}));const deleted=structuredClone(before);deleted.products=[];assert.throws(()=>authorizeChanges(before,deleted,{id:'manager',role:'Manager'}));});
