const router=require('express').Router();
const controller=require('./expense-voucher.controller');
router.param('id',(req,res,next,value)=>{try{req.params.id=require('../../utils/validation').id(value);next();}catch(e){next(e);}});
router.use(...require('../../middleware/protect-resource')('EXPENSE_VOUCHER'));
router.get('/',controller.list);
router.get('/:id',controller.getOne);
router.post('/',controller.create);
router.put('/:id',controller.update);
router.patch('/:id/post',controller.post);
router.patch('/:id/cancel',controller.cancel);
module.exports=router;
